### ISSUE TITLE
Config.json example in readme

### ISSUE THREAD

**Issue by rbholland** [codyc1515/homebridge-orbit-bhyve#15]
Is there an entry required in config.json, or should this work upon installation of the plugin? Could you add a config.json example in the readme? Thank you

**Comment by mitch7391** [comment]
Not sure which of the devices you have, but if it is the multi zone controller then this is what you need:

   {
            "accessory": "OrbitBHyve",
            "name": "Orbit B-Hyve",
            "email": "joe@bloggs.com",
            "password": "mySECUREpassword",
            "zones": 4
        }

**Comment by leehadassin** [comment]
I have set up my config.json exactly like that - I know the credentials are correct as it is getting information into HomeKit(feedback of system running). I have four zone and HomeKit shows 4 zones so that part is correct too. Not sure why the default 300 is not getting passed through when I try do a manual run

**Comment by rbholland** [comment]
Worked great. Thank you! Looking forward to seeing if anyone can figure out how to run multiple controllers.

**Comment by mitch7391** [comment]
No worries mate! :)
